### ISSUE TITLE
Computing var_loss

### ISSUE THREAD

**Issue by MLbyML** [davyneven/SpatialEmbeddings#18]
Hello Davy @davyneven 

I was wondering if instead of saying [here](https://github.com/davyneven/SpatialEmbeddings/blob/213b5fa9900513818365d98e7db9f2067633d94d/src/criterions/my_loss.py#L89):
```
 var_loss = var_loss + torch.mean(torch.pow(sigma_in - s.detach(), 2))
```
One should rather say: 
```
 var_loss = var_loss + torch.mean(torch.pow(sigma_in - s[..., 0].detach(), 2))
```

I suggest this because `sigma_in` is of shape `2 x N` and `s` is of shape `2 x 1 x 1`, and subtracting two tensors of different shapes could lead to strange consequences (maybe?). 

For example:
```python3
import numpy as np
sigma_in = np.array([[1.0 ,2.0, 3.0], [2.0, 4.0, 6.0]]) 
sigma_in = torch.from_numpy(sigma_in) # shape is 2 x 3
>>> sigma_in
tensor([[1., 2., 3.],
        [2., 4., 6.]], dtype=torch.float64)
s = sigma_in.mean(1).view(2, 1, 1)  
>>> s
tensor([[[2.]],
        [[4.]]], dtype=torch.float64) # shape is 2 x 1 x 1
result = sigma_in - s.detach() # shape is 2 x 2 x 3
>>> result tensor([[[-1.,  0.,  1.],
         [ 0.,  2.,  4.]],
        [[-3., -2., -1.],
         [-2.,  0.,  2.]]], dtype=torch.float64)
result_edited = sigma_in - s[..., 0].detach() # shape is 2 x 3
>>> result_edited
tensor([[-1.,  0.,  1.],
        [-2.,  0.,  2.]], dtype=torch.float64)
```
Just wanted to ask if the current way is intended. Wouldn't we want the correct margin bandwidth dimension to be subtracted instead of all (2 x 2) subtractions? Thank you!

**Comment by davyneven** [comment]
Hi Manan, you are absolutely right! Nasty bug, thanks for pointing this out. Will commit the fix.

**Comment by lmanan** [comment]
Awesome. Thank you!
