### ISSUE TITLE
Datasets expect Cityscapes

### ISSUE THREAD

**Issue by xck36** [davyneven/SpatialEmbeddings#2]
Hi, as mentioned in the CVPR version of your paper, do you have some results on other datasets expect Cityscapes?

**Comment by davyneven** [comment]
Hi, we are actually working on a follow-up paper, which will include more datasets. If we find time, we will add results on different datasets as well. But don't hold back to try the code on other datasets yourself.

**Comment by xck36** [comment]
> Hi, we are actually working on a follow-up paper, which will include more datasets. If we find time, we will add results on different datasets as well. But don't hold back to try the code on other datasets yourself.

Okay, thanks!
