### ISSUE TITLE
How to choose the value of n_sigma

### ISSUE THREAD

**Issue by Croooooow** [davyneven/SpatialEmbeddings#6]
It looks like a one channel sigma map works well. And from the code we can see that the sigma map can be multi channels accordding to the `n_sigma`.  Does this make differences and how to choose a proper value?

**Comment by davyneven** [comment]
Hi, as mentioned in the paper, a scalar sigma will result in a circular region, while a two dimensional sigma can result in a elliptical one. For rectangular objects, the latter can give some improvement.
