### ISSUE TITLE
how to use cityscapesScripts to evaluate the txt files saved by running test.py

### ISSUE THREAD

**Issue by detectRecog** [davyneven/SpatialEmbeddings#9]
Hi, could you please tell me the instructions to use cityscapesScripts to compute AP and AP_{50}.

Thanks in advance.

**Comment by Croooooow** [comment]
Hi, to evalute you results on cityscape, you need to format it into cityscape-type. This is done in `test.py` from line 84 in this repo.
You can also refer to the [cityscape repo](https://github.com/mcordts/cityscapesScripts). There are detail instructions in` evaluation/evalInstanceLevelSemanticLabeling.py`.
